apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: saisrivathsan98/myapp
        ports:
        - containerPort: 5000
          
        